name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build --if-present || npm run build
      - name: Check Vercel secrets
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          echo "Checking Vercel secrets visibility (will print present/missing)"
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "VERCEL_TOKEN: MISSING"
            exit 1
          else
            echo "VERCEL_TOKEN: present"
          fi
          if [ -z "$VERCEL_PROJECT_ID" ]; then
            echo "VERCEL_PROJECT_ID: MISSING"
          else
            echo "VERCEL_PROJECT_ID: present"
          fi
          if [ -z "$VERCEL_ORG_ID" ]; then
            echo "VERCEL_ORG_ID: MISSING (optional)"
          else
            echo "VERCEL_ORG_ID: present"
          fi
        shell: bash
      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ./
          vercel-args: '--prod'
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
